language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - EMULATOR_API=21
  - ADB_INSTALL_TIMEOUT=5
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - secure: E8gyIMzqj8VUHFyoHVQyrFgGCvQ2Txn28HwfkrVY5qDxtEG+R22FQl2dE/eTvhQm79Whxm8yLWPRo29PGZzPLdnrs5vAdZUAZYjn9sn+8C3MTQ5Hl0U/ZmqN9i8wN6OBLyf0ZBgXO/N9aRQKJXZBFFitlWGWoDv8TzgDQOjKiDKyuVC/v+SaXTnju2LcG6722BPirxtdy9Kttuwyh9YEvEihfPwYaPYAls7Gj3w33I4FHvVBZLV3i9iXC5hbBaV8TSaYP5f8w+xgRisgMILcZgD/CiOz2oazftqI36/zFTVVZxdMxKoC1Pj4VW6yZjBRDlSAiPKjm8QYHp/Pq3EkE2Mg6Fez5xcU5wMDFTFj8RXg39E9nGnXtLMBcdCxLJ4xBVL912/Ggg423icuYH+2pfaR0pRFDyTmaSbKsg0pvPdBnBiWG9hPnKeI2BD4c6LxGXBR9GpYBIDC5uhz1E94Lb5+6vADDB1Hr0Bi6NW3LxzP0fn8jvZalOgsgKw4GYuH1SLr5BNUhAXFQzt3e6jnNQEEKewm36LLcAZlYWE35u+PCszujJdP4nc6b4XamByOaz3m3+zYRdf3TETVljIGX81olpVCHWpXQeuUV1/hBwpHwdWsmOlaJmBRd1mGC7h0+V0shkG6rzRQxQtmTO/+Q520hrELiKtaNzCGhaKJJFw=
  - secure: "OJLTTLnXkNmQFaVSd7fPv4d1GLVIHmFgBNBDD8D3RuN+DStx/q06aRA/hymBCdmicj0FVLpSQszbvIK7cV2S+1opO/DGtywUrmV/8X/Ldo/Egz8nNvtCFloLZ1UuHCN1AIdwyzXxxGlntYc+nRJdcGWH7WpMI8nreBkjPj93oK1hTc/wyrdPOhdg/UCfJePexVAKmavqWF/kTLK2lUg/S1Y/w5r2kD3nYDyTnP3c4O/X4NMLp++HY9zyFyyQ7C4EfGCX58z0Lbryl3RLbt3wm6l5YGqX1kZxqkqXrfi8WqNGs+D3QAnftf5Vb6ceDeJNNwor1jTrrR0Z0uJ1iiZ4+Yu8tWzALPwVAgW00WHbjlfI8wZWcLdGDV4xi491mqAr+HXV6Q2KWlnZ9/HVp/Y1aSeTXi7QcSrabB2STXUu/AOQPn2s+NppR6PrNs5+O40HNIgF+3mYCnaSuDAbcQbjDWjXTlcTVTZaNqLkqRZuE51DLzYTqeREOw8qtkR15ZiJQsqCJhs/2Hr/u3Wxfkr9if45ctfrd8j+EwaWskg/sWYTRsWv5p1D6jTAYTpXq0WHJuWD6kL1SLXX9d4HzP233/Rt3mJiPAZy3SO9bH6uXDz5v3LlhLM5eFYPWwayGyGng/GfSYG19XT0aLBB47CJ0XIWnVPr1MxTz1YZ3we0a6E="
  - secure: "193fLSY+GWlE6ubMb5B2JtQuuMhe1hSO7XcooZWQI6beD6WnVyUUllupJLYR603khDmo3UJe7X/8pf3mvphbR7kq+dmSo9ymqMkDpHoobFceakgFJzrw2nGuajCBmiYHeuK7RuZ8nQAvPSOaCMTRZ2auu8AryOJvPebE9puNbTmq9VCh8CXFOPz0igYkIFY5lqpHzl6TS1Jl4w21kbXmNQFJAwOau0qHL5bVIOOz5vAaLKrhbMfpZAb5ZYNECo2WsgobxkOKrFwe/mGRCEvISha+ZeYj4Oajt+wmpONGfrkZ6h8oXSNw7Qf2+OKKaxj2PfzCtrgeWXzeczwV1EMglx9Gcnc0L0Wc+m6ANKG7ve1TgTrGL7UpPydQ4QuD+IdziRgxiTBmzAO27rcOTzcgei36Pl78qga5LJAuIAJLEzz2CRCacy+kamMaeQ1Yl6nq6fNHoExwIFtsw8sWvkSqrMo8CDhLTdub71sC/gk+jX4qbL0stXkS64LVgX66NhJQxpIAQie8Mms2H3VFtWcEf9ZS40rtabDt+WSFag7QeWtNmsp94iiKwm1iM1nRi30VGFsin/uaISXuY25IL0nu3cxmRiqDQuAom7VGANOvDSddl4EUgS/HlTSHu/wlMEKUmy3GcRFH11PCeTYODwBLNU2U/kRj7zQlICdMa0eiHVs="
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.2
  - build-tools-27.0.3
  - android-26
  - android-26
  - extra-google-google_play_services
  - addon-google_apis-google-26
   - addon-google_apis-google-21
  - extra-google-m2repository
  - extra-android-support
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-26
  - sys-img-armeabi-v7a-android-21
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- chmod +x gradlew
#-openssl aes-256-cbc -K $encrypted_6cae81c4f41c_key -iv $encrypted_6cae81c4f41c_iv -in keystore.jks.enc -out keystore.jks -d
- "./gradlew dependencies || true"
- pip install --user codecov
addons:
  sonarcloud:
    organization: t00180243-github
    token:
      secure: 997c8e9fb9b2709d2007f80119950ddca7071034
before_script:
- android list targets
- android list sdk --extended --no-ui --all
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#script:
"./gradlew assembleDebug && ./gradlew lintDebug &&./gradlew testDebug"
after_success:
- "./gradlew jacocoTestReport coveralls"
- codecov
- sonar-scanner

before_deploy:
- cp $TRAVIS_BUILD_DIR/.keystore.jks $HOME
- cd app/build/outputs/apk/
#- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk calculator_keystore
# Verification
#- jarsigner -verify app-release-unsigned.apk
#- "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk calculator.apk"

deploy:
   provider: releases
   file: "app/build/outputs/apk/release/app-release.apk"
   skip_cleanup: true
   on:
       repo: t00180243/DevOps_MobileApp
       branch: master
       jdk: oraclejdk8
   api_key:
       secure: "qJ3KDEcgkKzonBPpScXupzAAvlIM0YDP/OA2VAExSDliENLUOAPzLJT6zRFY6eOBoett01eARXxYucaeaZsmPwEQEOz8JOQI8l9n3BggtFwy7Q7kzCExMWtpxVC652CuqGvPF1E8yVtvBCHJAg+Dh+Gd0dDZgZou+bkkKH9eRmjYAiXXEUtKI+gYM+7B1jXIlHQWYQun8RtuzApbemBgNGWViaUo9peW6VxDrLdms+yYVwoRE/+W9qbHDly6s4EtrU8W8O4i97DBmqkGLda+zlcwhB60Z6fSu3KgpHH719J/RBc1ZIRXUAjogOIQ3TlCvj+T3KoPgus6mlaMGA78BifOl4ojW0isoAfDzfvNvcm/4AeyKG63nJibmL/VWThfiJR8OFZWT5RVvfKCNt0ZDsqKRFQbvseC8lNvU/V0xVjsZS2U/f2Uv14z7zJ39sKQznRqwjUguIo16QU60oHWzxFZhulWGBv+UT9HfuntX06d8bG1refS7FjLi39W5h5//Z8WCB1t1z6alvuGZPZJSVcsAPyINeC9MNCdJnkbBQXBAM9sOhES79f1kpjnpPicrzIqjo1OMtXRUY4kXOMLukTAzjYVz4KyVbpdZiDzOuEW6L/ZBpLJdwiuH5m8H0/tHi0zrAEGujZ2/BklxhUYDtV79MJLvy++4R3k8FDOSKE="
  #provider: testfairy
  #api-key:
    #secure: fQNOi5gygAGY+K1fCHwXCwYZNG4VW+WGzigQ3zfJ5rOG6Y1KIDk2bprmtnzooJ7s4qx2YJVsCwT/ML1M+VFs4WigllXX0+mLSBal1JTaYQ5Hf4dMrFI3KVWpRbh9cEW/OT+podDxYM8o9BbFbhiMEb2HPM4cLttd0xoNUHwOTQ0LFyTx30udp956B/hGuKtNt5fnKza0dz9Gy4GU28xGhQuiZxE3NAITu4Di7J1VzDHm8sXa/JOk37mM3mfXkLrUxNmQcvLtmBSu0tKf3N2N+/WgkcwMvjaSK5s60Vq9Osr1ckOvuMPlhd0AIGXsZGpgWc0bKqQf+2F5lUKF6TirQefb+bGlEBY7Ht3dJTLUQ0ne0PLPW/H9Pe6c+Oz5bX3ML1VWPS9EyuNK0iZEznBor2GVWq5dZK0H6F9pPjbleWzNAkQbOMoU3dTW5ubNgFTZC6UXFhc1bOP/N90gOwPflAKNvO8J3ZjcWJK2l8ayQ7Av/eNBq/7/Bs7pSZ0mCmWrRmAu4QNP1/STwjJa7KiFeIWTkfr254W88QwZssRJ3lFIB9hNvo79fg66hg6LOi8ZO9VuchZDOuYzLwgtAUC6llxwKojPO7PpnrkMl36t04d2IlJwgYCscEN9/SK5YnblcEo6ptXETYqxI2lDlE8+F4aqt7vdBCsnQP063bP8RiE=
  #app-file: app/build/outputs/apk/release/app-release.apk
  #keystore-file: C:/keystore.jks
