language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - EMULATOR_API=21
  - ADB_INSTALL_TIMEOUT=5
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - secure: E8gyIMzqj8VUHFyoHVQyrFgGCvQ2Txn28HwfkrVY5qDxtEG+R22FQl2dE/eTvhQm79Whxm8yLWPRo29PGZzPLdnrs5vAdZUAZYjn9sn+8C3MTQ5Hl0U/ZmqN9i8wN6OBLyf0ZBgXO/N9aRQKJXZBFFitlWGWoDv8TzgDQOjKiDKyuVC/v+SaXTnju2LcG6722BPirxtdy9Kttuwyh9YEvEihfPwYaPYAls7Gj3w33I4FHvVBZLV3i9iXC5hbBaV8TSaYP5f8w+xgRisgMILcZgD/CiOz2oazftqI36/zFTVVZxdMxKoC1Pj4VW6yZjBRDlSAiPKjm8QYHp/Pq3EkE2Mg6Fez5xcU5wMDFTFj8RXg39E9nGnXtLMBcdCxLJ4xBVL912/Ggg423icuYH+2pfaR0pRFDyTmaSbKsg0pvPdBnBiWG9hPnKeI2BD4c6LxGXBR9GpYBIDC5uhz1E94Lb5+6vADDB1Hr0Bi6NW3LxzP0fn8jvZalOgsgKw4GYuH1SLr5BNUhAXFQzt3e6jnNQEEKewm36LLcAZlYWE35u+PCszujJdP4nc6b4XamByOaz3m3+zYRdf3TETVljIGX81olpVCHWpXQeuUV1/hBwpHwdWsmOlaJmBRd1mGC7h0+V0shkG6rzRQxQtmTO/+Q520hrELiKtaNzCGhaKJJFw=
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.2
  - build-tools-27.0.3
  - android-26
  - android-26
  - extra-google-google_play_services
  - addon-google_apis-google-26
  - extra-google-m2repository
  - extra-android-support
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-26
  - sys-img-armeabi-v7a-android-27
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- chmod +x gradlew
- "./gradlew dependencies || true"
- pip install --user codecov
addons:
  sonarcloud:
    organization: t00180243-github
    token:
      secure: 997c8e9fb9b2709d2007f80119950ddca7071034
before_script:
- android list targets
- android list sdk --extended --no-ui --all
script:
- "./gradlew assembleDebug && ./gradlew lintDebug &&./gradlew testDebug"
after_success:
- "./gradlew jacocoTestReport coveralls"
- codecov
- sonar-scanner
#deploy:
  #provider: testfairy
  #api-key: "a318a4d10fbe3a8121febce3180c00c2436f0389"
  #app-file: app/build/outputs/apk/debug/app-debug.apk
  #skip_cleanup: true

deploy:
  provider: releases
  api_key: "fa5622c45a5ec14ff15f8c0c8e57b3fea539f2c0"

